config/routes.rb
VentasAkdemia::Application.routes.draw do
  
  
  resources :schools

  root :to => 'schools#index'

end

app/models/contact_status.rb
class ContactStatus < ActiveRecord::Base
  attr_accessible :name
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  attr_accessible :email, :name, :phone
  
  belongs_to :school
  
end

app/models/principal.rb
class Principal < ActiveRecord::Base
  attr_accessible :email, :name, :phone
  
  belongs_to :school
  
end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :city, :email, :name, :phone, :state, :note, :address, :school_system_id, :school_group_ids, :number_of_students
  attr_accessible :is_public, :tuition, :guardian_attributes, :principal_attributes, :contact_status_id
  
  
  belongs_to :school_system
  belongs_to :contact_status
  has_one :principal
  has_one :guardian
  has_many :school_groups, :through => :school_types
  has_many :school_types
  
  accepts_nested_attributes_for :principal, :guardian
  
  validates_presence_of :contact_status_id, :city, :email, :name, :phone, :state, :school_system_id, :number_of_students
  validates_inclusion_of :is_public, :in=> [true,false]
  
  def previous
    School.find_by_id(self.id - 1)
  end
  
  def next
    School.find_by_id(self.id + 1)
  end
  
end

app/models/school_group.rb
class SchoolGroup < ActiveRecord::Base
  attr_accessible :name
  
  has_many :schools, :through => :school_type
  has_many :school_types
end

app/models/school_system.rb
class SchoolSystem < ActiveRecord::Base
  attr_accessible :name
end

app/models/school_type.rb
class SchoolType < ActiveRecord::Base
  belongs_to :school
  belongs_to :school_group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])
    unless (@school.id-1) == 0
      @previous_school = School.find(@school.id-1)
    end
    @next_school = School.find(@school.id+1)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new
    @guardian = @school.build_guardian
    @principal = @school.build_principal


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
    if @school.guardian.nil?
      @guardian = @school.build_guardian
      @principal = @school.build_principal
    end
    unless (@school.id-1) == 0
      @previous_school = School.find(@school.id-1)
    end
    @next_school = School.find(@school.id+1)
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'Se guardo el colegio con exito' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>VentasAkdemia</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= yield :head %>
</head>
<body>
	<div class="container">
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<ul class="nav">
						<li>
							<%= link_to 'Colegios', schools_path() %> 
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container-fluid">
			<div class="span12">
		<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/schools/_form.html.haml
%br
%br
.row-fluid
= simple_form_for(@school, :html => { :class => "form-horizontal"} ) do |f|

	.span5
		%fieldset
			= f.input(:contact_status_id, :collection => ContactStatus.all, :include_blank => 'Please Select', :label => 'Estatus de Contacto')
			= f.input :name, :label => 'Nombre'
			= f.input :city, :label => 'Ciudad'
			= f.input :state, :label => 'Estado'
			= f.input :email
			= f.input(:school_system_id, :collection => SchoolSystem.all, :include_blank => 'Please Select', :label => 'Sistema de Informacion')
			= f.input :phone, :label => 'Telefono'
			= f.input :address, :as => :text, :input_html => {:rows=>"5"}, :label => 'Direccion'
			= f.input :is_public, :as => :radio_buttons, :collection => [["Publica", true], ["Privada", false]], :label => 'Tipo de Institucion' 
			= f.input :number_of_students, :as => :integer, :label => 'Numero de Estudiantes'
			= f.input :school_group_ids, :collection =>  SchoolGroup.all , :as => :check_boxes, :label => 'Tipo de Colegio'
			= f.input :tuition, :label => 'Costo de la matricula'
			= f.input :note, :as => :text, :input_html => {:rows=>"5"}, :label => 'Nota'
	.span5
		%fieldset
			%h3 Sociedad de Padres y Representantes
			= f.fields_for :guardian do |g|
				= g.input :name, :label => 'Nombre'
				= g.input :phone, :label => 'Telefono'
				= g.input :email
			%h3 Director
			= f.fields_for :principal do |g|
				= g.input :name, :label => 'Nombre'
				= g.input :phone, :label => 'Telefono'
				= g.input :email
			= f.submit 'Guardar Colegio', :class => 'btn btn-large btn-primary'
			= link_to 'Ir a Perfil', @school, :class=> "btn"

	

app/views/schools/edit.html.erb
<h1><%= @school.name%></h1>
<div class="row-fluid">
		<div class="span12">

			<%= render 'form' %>

			

	</div>
	</div>
	
<div class="row-fluid">
	<ul class="pager">
		<%unless @school.previous.nil? %>
		<li>
			<%= link_to 'Previous', edit_school_path(@school.previous) %>
		</li>
		<%end%>

		<li>
			<%= link_to 'Next', edit_school_path(@school.next) %>
		</li>
	</ul>
</div>

app/views/schools/index.html.erb
<% content_for :head do %>
<%javascript_include_tag "dataTables.bootstrapPagination"%>

  <script type="text/javascript" charset="utf-8">
 jQuery(document).ready(function(){
    
	jQuery('#schools').dataTable({
    "sPaginationType": "bootstrap"
    });



    jQuery.extend( jQuery.fn.dataTableExt.oStdClasses, {
    "sWrapper": "dataTables_wrapper form-inline"
    } );
    });

</script>

<% end %>
<h1>Colegios de Venezuela</h1>

<table class="table table-striped" id="schools">
	<thead>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th>Phone</th>
    <th>Email</th>
		<th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	</thead>
	<tbody>
<% @schools.each do |school| %>
  <tr>
    <td><%= school.name %></td>
    <td><%= school.city %></td>
    <td><%= school.state %></td>
    <td><%= school.phone %></td>
    <td><%= school.email %></td>
		<td>
		<% unless school.contact_status.nil?%>
			<%= school.contact_status.name %>
		<%end%>
			</td>
    <td><%= link_to 'Show', school %></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.haml
- flash.each do |name, msg|
	%div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
		%a.close{"data-dismiss" => "alert"} ×
		= msg
.row-fluid
	.span12
		%h1
			= @school.name
		%h2
			- if @school.is_public == true
				Publica
			- if @school.is_public == false
				Privada
		%br
		.span5
			%h3
				Datos del Colegio
			%p
				%b Numero de Estudiantes:
				= @school.number_of_students
			%p	
				%b Ciudad:
				= @school.city
			%p
				%b Estado:
				= @school.state
			%p
				%b Sistema escolar:
				- unless @school.school_system.nil?
					= @school.school_system.name
			%p
				%b Tipo de Colegio:
				%ul
				- @school.school_groups.each do |school_group|
					%li
						= school_group.name
			%p
				%b Telefono:
				= @school.phone
			%p
				%b Email:
				= @school.email
			%p
				%b Direccion:
				= @school.address
			%p
				%b Nota:
				= @school.note
			%br
		.span6
			%h3
				Sociedad de Padres y Representantes
			%p
				%b Nombre de representante:
				- unless @school.guardian.nil?
					= @school.guardian.name
			%p		
				%b Email de representante:
				- unless @school.guardian.nil?
					= @school.guardian.email
			%p	
				%b Telefono:
				- unless @school.guardian.nil?
					= @school.guardian.phone
			%h3
				Director
			%p
				%b Nombre de representante:
				- unless @school.guardian.nil?
					= @school.guardian.name
			%p		
				%b Email de representante:
				- unless @school.guardian.nil?
					= @school.guardian.email
			%p	
				%b Telefono:
				- unless @school.guardian.nil?
					= @school.guardian.phone
.row-fluid
	.span12
					
		= link_to 'Edit', edit_school_path(@school), :class=> "btn"
		%ul.pager
			- unless @previous_school.nil?
				%li
					= link_to 'Previous', school_path(@previous_school)
				%li
					= link_to 'Next', school_path(@next_school)